# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
    - covr
    - pkgdown

after_success:
    - Rscript -e 'covr::codecov()'
    - R CMD INSTALL .
    - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  keep_history: true
  local_dir: docs
  on:
    branch: master
